services:
  postgres:
    image: 'postgres:latest'
    container_name: synch-pgsql
    environment:
      - 'POSTGRES_DB=synch'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5432:5432'

volumes:
  postgres_data: