services:
  postgres:
    image: 'postgres:latest'
    container_name: synch-pgsql
    environment:
      - 'POSTGRES_DB=${DB_SYNC}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASS}'
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_SYNC}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_PROFILES_ACTIVE: dev
      JWT: ${JWT}
    volumes:
      - ./src:/app/src
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
    container_name: synch-app
    command: ./mvnw spring-boot:run

volumes:
  postgres_data: