services:
  postgres:
    image: 'postgres:latest'
    container_name: synch-pgsql
    environment:
      - 'POSTGRES_DB=${DB_SYNC}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASS}'
    ports:
      - '5432:5432'

volumes:
  postgres_data: