CREATE TABLE expense
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    month            VARCHAR(255)                            NOT NULL,
    amount           DOUBLE PRECISION                        NOT NULL,
    finance_table_id BIGINT,
    CONSTRAINT pk_expense PRIMARY KEY (id)
);

CREATE TABLE finance_table
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_finance_table PRIMARY KEY (id)
);

CREATE TABLE finance_table_user
(
    finance_table_id BIGINT NOT NULL,
    user_id          BIGINT NOT NULL
);

ALTER TABLE expense
    ADD CONSTRAINT FK_EXPENSE_ON_FINANCE_TABLE FOREIGN KEY (finance_table_id) REFERENCES finance_table (id);

ALTER TABLE finance_table_user
    ADD CONSTRAINT fk_fintabuse_on_finance_table FOREIGN KEY (finance_table_id) REFERENCES finance_table (id);

ALTER TABLE finance_table_user
    ADD CONSTRAINT fk_fintabuse_on_user FOREIGN KEY (user_id) REFERENCES users (id);